Remove some more multiple server related code/scripting.

diff --git a/coda-src/scripts/vice-setup-rvm.in b/coda-src/scripts/vice-setup-rvm.in
--- a/coda-src/scripts/vice-setup-rvm.in
+++ b/coda-src/scripts/vice-setup-rvm.in
@@ -52,7 +52,6 @@ if [ "x${conf}" != x/dev/null ] ; then
   haveconf=1
 else
   haveconf=0
-  numservers=1
 fi
 
 # test on Solaris doesn't have a -e flag :-(
@@ -91,11 +90,6 @@ echo
 echo WARNING: these choices are not easy to change once you are up and running.
 echo
 
-if [ $numservers -gt 1 ]; then
-  echo For multiple servers on the same machine, you will need to specify a log
-  echo partition and a metadata partition for each server you plan to run.
-fi
-
 yesno=""
 until [ "x$yesno" != x ]; do
    echon "Are you ready to set up RVM? [yes/no] "
@@ -109,198 +103,160 @@ else
 fi
 
 #
-# Do the following for each server ...
+# we need a size and partition for the log.
 #
+log=""
+until [ "x$log" != x ]; do
+    echon "What will be your log file (or partition)? "
+    read log
+done
 
-n=1
-while [ $n -le $numservers ]; do
-
-    if [ $numservers -gt 1 ]; then
-	conf="`@sbindir@/codaconfedit server_$n.conf`"
-	if [ "x$conf" != x/dev/null ]; then
-	    . $conf
-	fi
-	if [ x$hostname != x ]; then
-	    echo "Configuring for server $n ($hostname)."
-	else
-	    echo "No initial server_$n.conf found, something went wrong with vice-setup?"
-	    exit 1
-
-#	    echo "Configuring for server $n."
-#	    hostname=""
-#	    while [ x$hostname = x ]; do
-#		echon "What is the hostname for server $n? "
-#		read hostname
-#	    done
-#	    echo > $conf << EOF
-#hostname="$hostname"
-##rvm_log=""
-##rvm_data=""
-##rvm_data_length=""
-##mapprivate=""
-#EOF
-	fi
-    fi
-
-    #
-    # we need a size and partition for the log.
-    #
-    log=""
-    until [ "x$log" != x ]; do
-	echon "What will be your log file (or partition)? "
-	read log
-    done
-
-    logsize=""
-    until [ "x$logsize" != x ]; do
-	echo
-	echo "The log size must be smaller than the available space in the log"
-	echo "partition. A smaller log will be quicker to commit, but the log"
-	echo "needs to be large enough to handle the largest transaction. A"
-	echo "larger log also allows for better optimizations. We recommend"
-	echo "to keep the log under 30M log size, many people have successfully"
-	echo "used as little as 2M, and 20M has worked well with our servers."
-	echon "What is your log size? (enter as e.g. '20M') "
-	read logsize
-	echo
-    done
-
-    data=""
-    until [ x$data != x ]; do
-	echon "Where is your data file (or partition)? "
-	read data
-    done
-
-    datasize=""
-    until [ x$datasize != x ]; do
-	echo
-	echo  "The amount of RVM we need to store the metadata for a given"
-	echo  "amount file space can vary enormously. If your typical data set"
-	echo  "consists of many small files, you definitely need more RVM, but"
-	echo  "if you tend to store large files (mp3s, videos or image data)"
-	echo  "we don't need all that much RVM."
-	echo
-	echo  "Here are some random samples,"
-	echo  "  mp3 files     ~0.08MB RVM per GB."
-	echo  "  jpeg images   ~0.50MB RVM per GB."
-	echo  "  email folders ~37.8MB RVM per GB (maildir, 1 file per message)"
-	echo  "  netbsd-pkgsrc  ~180MB RVM per GB (large tree but not much data)"
-	echo
-	echo  "To get a more precize number for your dataset there is a small"
-	echo  "tool (rvmsizer) which can reasonably predict the amount of RVM"
-	echo  "data we need for a file tree."
-	echo
-	echo  "Remember that RVM data will have to be mmapped or loaded"
-	echo  "into memory, so if anything fails with an error like"
-	echo  "RVM_EINTERNAL you might have to add more swap space."
-	echo
-	echo "What is the size of you data file (or partition)"
-	echon "[32M, 64M, 128M, 256M, 512M, 768M, 1G]: "
-	read datasize
-
-	case $datasize in
-	    32[mM] | 64[mM] | 128[mM] | 256[mM] )
-		;;
-	    512[mM] | 768[mM] | 1[gG] )
-		echo
-		echo "!!!!!!!!!!!!!!"
-		echo Your size is an experimental size.  Be warned!
-		echo You may want to run with private mapping for RVM.
-		echo
-		;;
-	    * )
-		echo "You have selected an unsupported size and this script"
-		echo "will not setup your RVM with this size.  Are you sure"
-		echon "you want this size?  (yes/no) "
-		yesno=
-		read yesno
-		if [ x$yesno != xyes ]; then
-		    datasize=""
-		fi
-		;;
-	esac
-    done
-
-    log=`fullname $log`
-    data=`fullname $data`
-
-    # strip non-digit characters
-    datasize="`echo "$datasize" | sed -n 's/\([0-9]*\).*/\1/p'`"
-    # Assume values <= 4 are in gigabytes, else we assume megabytes
-    [ "$datasize" -le 4 ] && datasize="`expr "$datasize" \* 1024`"
-
+logsize=""
+until [ "x$logsize" != x ]; do
     echo
-    echo --------------------------------------------------------
-    echo WARNING: DATA and LOG  partitions are about to be wiped.
-    echo --------------------------------------------------------
+    echo "The log size must be smaller than the available space in the log"
+    echo "partition. A smaller log will be quicker to commit, but the log"
+    echo "needs to be large enough to handle the largest transaction. A"
+    echo "larger log also allows for better optimizations. We recommend"
+    echo "to keep the log under 30M log size, many people have successfully"
+    echo "used as little as 2M, and 20M has worked well with our servers."
+    echon "What is your log size? (enter as e.g. '20M') "
+    read logsize
     echo
-    echo "  --- log area: $log, size $logsize."
-    echo "  --- data area: $data, size $datasize MB."
-    echo
-    answer=""
-    until [ "x$answer" != x ]; do
-	echon "Proceed, and wipe out old data? [y/n] "
-	answer=n
-	read answer
-    done
-    if [ "x$answer" = xn -o "x$answer" = xno -o "x$answer" = xN -o \
-	"x$answer" = xNo ]; then
-	exit 1
-    fi
+done
 
+data=""
+until [ x$data != x ]; do
+    echon "Where is your data file (or partition)? "
+    read data
+done
+
+datasize=""
+until [ x$datasize != x ]; do
     echo
-    @RVMUTL@ > /dev/null  << EOF
+    echo  "The amount of RVM we need to store the metadata for a given"
+    echo  "amount file space can vary enormously. If your typical data set"
+    echo  "consists of many small files, you definitely need more RVM, but"
+    echo  "if you tend to store large files (mp3s, videos or image data)"
+    echo  "we don't need all that much RVM."
+    echo
+    echo  "Here are some random samples,"
+    echo  "  mp3 files     ~0.08MB RVM per GB."
+    echo  "  jpeg images   ~0.50MB RVM per GB."
+    echo  "  email folders ~37.8MB RVM per GB (maildir, 1 file per message)"
+    echo  "  netbsd-pkgsrc  ~180MB RVM per GB (large tree but not much data)"
+    echo
+    echo  "To get a more precize number for your dataset there is a small"
+    echo  "tool (rvmsizer) which can reasonably predict the amount of RVM"
+    echo  "data we need for a file tree."
+    echo
+    echo  "Remember that RVM data will have to be mmapped or loaded"
+    echo  "into memory, so if anything fails with an error like"
+    echo  "RVM_EINTERNAL you might have to add more swap space."
+    echo
+    echo "What is the size of you data file (or partition)"
+    echon "[32M, 64M, 128M, 256M, 512M, 768M, 1G]: "
+    read datasize
+
+    case $datasize in
+        32[mM] | 64[mM] | 128[mM] | 256[mM] )
+            ;;
+        512[mM] | 768[mM] | 1[gG] )
+            echo
+            echo "!!!!!!!!!!!!!!"
+            echo Your size is an experimental size.  Be warned!
+            echo You may want to run with private mapping for RVM.
+            echo
+            ;;
+        * )
+            echo "You have selected an unsupported size and this script"
+            echo "will not setup your RVM with this size.  Are you sure"
+            echon "you want this size?  (yes/no) "
+            yesno=
+            read yesno
+            if [ x$yesno != xyes ]; then
+                datasize=""
+            fi
+            ;;
+    esac
+done
+
+log=`fullname $log`
+data=`fullname $data`
+
+# strip non-digit characters
+datasize="`echo "$datasize" | sed -n 's/\([0-9]*\).*/\1/p'`"
+# Assume values <= 4 are in gigabytes, else we assume megabytes
+[ "$datasize" -le 4 ] && datasize="`expr "$datasize" \* 1024`"
+
+echo
+echo --------------------------------------------------------
+echo WARNING: DATA and LOG  partitions are about to be wiped.
+echo --------------------------------------------------------
+echo
+echo "  --- log area: $log, size $logsize."
+echo "  --- data area: $data, size $datasize MB."
+echo
+answer=""
+until [ "x$answer" != x ]; do
+    echon "Proceed, and wipe out old data? [y/n] "
+    answer=n
+    read answer
+done
+if [ "x$answer" = xn -o "x$answer" = xno -o "x$answer" = xN -o \
+    "x$answer" = xNo ]; then
+    exit 1
+fi
+
+echo
+@RVMUTL@ > /dev/null  << EOF
 i $log $logsize
 q
 EOF
 
-    echo
-    if [ $? != 0 ]; then
-	echo Error in rvmutl. Exiting.
-	exit 1
-    fi
+echo
+if [ $? != 0 ]; then
+    echo Error in rvmutl. Exiting.
+    exit 1
+fi
 
-    echo LOG file has been initialized!
+echo LOG file has been initialized!
 
-    echo
+echo
 
-    # Convert requested RVM data size to bytes
-    dsparm="`expr "$datasize" \* 1048576`"
-    staticsize=1048576 # reserve 1MB for a static allocation area
-    rvmreserve=65536   # reserve 64K for RVM overhead (we need pagesize() bytes)
+# Convert requested RVM data size to bytes
+dsparm="`expr "$datasize" \* 1048576`"
+staticsize=1048576 # reserve 1MB for a static allocation area
+rvmreserve=65536   # reserve 64K for RVM overhead (we need pagesize() bytes)
 
-    # Use the remaining space for the dynamic heap
-    heapsize="`expr "$dsparm" - "$staticsize" - "$rvmreserve"`"
+# Use the remaining space for the dynamic heap
+heapsize="`expr "$dsparm" - "$staticsize" - "$rvmreserve"`"
 
-    # various other parameters
-    rvmstart=0x50000000
-    nlists=80
-    chunk=64
+# various other parameters
+rvmstart=0x50000000
+nlists=80
+chunk=64
 
-    parms="$dsparm $rvmstart $heapsize $staticsize $nlists $chunk"
+parms="$dsparm $rvmstart $heapsize $staticsize $nlists $chunk"
 
-    if [ $haveconf = 1 ] ; then
-	conffile="`basename $conf`"
-	@sbindir@/codaconfedit $conffile rvm_log $log
-	@sbindir@/codaconfedit $conffile rvm_data $data
-	@sbindir@/codaconfedit $conffile rvm_data_length $dsparm
-    else
-	echo "-rvm $log $data $dsparm" >> ${vicedir}/srv.conf
-    fi
+if [ $haveconf = 1 ] ; then
+    conffile="`basename $conf`"
+    @sbindir@/codaconfedit $conffile rvm_log $log
+    @sbindir@/codaconfedit $conffile rvm_data $data
+    @sbindir@/codaconfedit $conffile rvm_data_length $dsparm
+else
+    echo "-rvm $log $data $dsparm" >> ${vicedir}/srv.conf
+fi
 
-    echo
-    echo "Rdsinit will initialize data and log."
-    echo "This takes a while."
-    @RDSINIT@ -f $log $data $parms
+echo
+echo "Rdsinit will initialize data and log."
+echo "This takes a while."
+@RDSINIT@ -f $log $data $parms
 
-    if [ $? != 0 ]; then
-	echo Error in rdsinit. Exiting.
-	exit 1
-    fi
-
-    n=`expr $n + 1`
-    echo
-done
+if [ $? != 0 ]; then
+    echo Error in rdsinit. Exiting.
+    exit 1
+fi
 
 echo RVM setup is done!
 echo
diff --git a/coda-src/scripts/vice-setup-srvdir.in b/coda-src/scripts/vice-setup-srvdir.in
--- a/coda-src/scripts/vice-setup-srvdir.in
+++ b/coda-src/scripts/vice-setup-srvdir.in
@@ -32,7 +32,6 @@ echon() {
 # Configuration
 #
 vicedir=/vice
-numservers=1
 . "`@sbindir@/codaconfedit server.conf`"
 
 if [ x$hn = x ] ; then
@@ -48,114 +47,95 @@ if [ x$hn = x ] ; then
   fi
 fi
 
-n=1
-while [ $n -le $numservers ]; do
 
-    # server information prefix
-    if [ $numservers -gt 1 ]; then
-	srvprefix=${vicedir}/server_$n
-	. "`@sbindir@/codaconfedit server_$n.conf`"
-	hn=$hostname
-    else
-	srvprefix=${vicedir}
+#
+# Setting up the server directory
+#
+echo
+echo Directories on the server will be used to store container files
+echo that hold the actual data of files stored in Coda. Directory
+echo contents as well as metadata will be stored in the RVM segment
+echo that we already configured earlier.
+echo
+echo You should only have one container file hierarchy for each disk
+echo partition, otherwise the server will generate incorrect
+echo estimates about the actual amount of exportable disk space.
+echo
+
+echon 'Where shall we store your file data [/vicepa]? '
+srvdir=
+read srvdir
+
+if [ "x$srvdir" = x ]; then
+    srvdir=/vicepa
+fi
+
+# Create the directory if needed.  (Symlink is OK.)
+
+if [ -d "$srvdir" -o -h "$srvdir" ]; then
+    if [ -f "$srvdir/FTREEDB" ]; then
+    echo "An FTREEDB exists in $srvdir.  Clean up first and rerun $0"
+    echo "You may also want to clean up ${vicedir}/db/vicetab"
+    exit 1
     fi
-
-    #
-    # Setting up the server directory
-    #
-
-    echo
-    echo Directories on the server will be used to store container files
-    echo that hold the actual data of files stored in Coda. Directory
-    echo contents as well as metadata will be stored in the RVM segment
-    echo that we already configured earlier.
-    echo
-    echo You should only have one container file hierarchy for each disk
-    echo partition, otherwise the server will generate incorrect
-    echo estimates about the actual amount of exportable disk space.
-    echo
-    
-    if [ $numservers -gt 1 ]; then
-	echon "Where shall we store your file data for server $n ($hn) [/vicepa]? "
-    else
-	echon 'Where shall we store your file data [/vicepa]? '
+else
+    mkdir "$srvdir"
+    if [ $? != 0 ]; then
+        echo "Could not make $srvdir as a directory. Exiting."
+        echo "Run vice-setup-srvdir to repeat this step."
+        exit 1
     fi
-    srvdir=
-    read srvdir
+fi
+touch "$srvdir/FTREEDB"
 
-    if [ "x$srvdir" = x ]; then
-	srvdir=/vicepa
-    fi
-
-    # Create the directory if needed.  (Symlink is OK.)
-    
-    if [ -d "$srvdir" -o -h "$srvdir" ]; then
-	if [ -f "$srvdir/FTREEDB" ]; then
-	echo "An FTREEDB exists in $srvdir.  Clean up first and rerun $0"
-	echo "You may also want to clean up ${vicedir}/db/vicetab"
-	exit 1
-	fi
-    else
-	mkdir "$srvdir"
-	if [ $? != 0 ]; then
-	    echo "Could not make $srvdir as a directory. Exiting."
-	    echo "Run vice-setup-srvdir to repeat this step."
-	    exit 1
-	fi
-    fi
-    touch "$srvdir/FTREEDB"
-    
-    yesno=""
-    until [ "x$yesno" != x ]; do
-        echon "Shall I set up a vicetab entry for $srvdir (y/n) "
-	read yesno
-    done
-    if [ "x$yesno" = xy -o "x$yesno" = xyes -o "x$yesno" = xY ]; then
-	grep $srvdir ${vicedir}/db/vicetab >/dev/null 2>&1
-	if [ $? = 0 ]; then
-	    echo "$srvdir already in ${vicedir}/db/vicetab. Please clean up first."
-	    exit 1
-	fi
-	
-	size=""
-	until [ "x$size" != x ]; do
-	    echo "Select the maximum number of files for the server."
-	    echo "[256K, 1M, 2M, 16M]: "
-	    read size
-	    case "$size" in
-		256[kK] )
-		    echo "$hn   $srvdir   ftree   width=64,depth=3" \
-			 >> ${vicedir}/db/vicetab
-		    ;;
-		1[mM] )
-		    echo "$hn   $srvdir   ftree   width=32,depth=4" \
-			 >> ${vicedir}/db/vicetab
-		    ;;
-		2[mM] )
-		    echo "$hn   $srvdir   ftree   width=128,depth=3" \
-			>> ${vicedir}/db/vicetab
-		    ;;
-		16[mM] )
-		    echo "$hn   $srvdir   ftree   width=256,depth=3" \
-			>> ${vicedir}/db/vicetab
-		    ;;
-		* )
-		    echo "Choose from one of the listed values."
-		    size=""
-		    ;;
-	    esac
-	done	      
-	echo
-	echo "Server directory $srvdir is set up!"
-    else
-	echo
-	echo  "Read vicetab(5) for set up info."
-	echo
-	echo  "Press return to continue"
-	read ok
-    fi
-
-    echo
-
-    n=`expr $n + 1`
+yesno=""
+until [ "x$yesno" != x ]; do
+    echon "Shall I set up a vicetab entry for $srvdir (y/n) "
+    read yesno
 done
+if [ "x$yesno" = xy -o "x$yesno" = xyes -o "x$yesno" = xY ]; then
+    grep $srvdir ${vicedir}/db/vicetab >/dev/null 2>&1
+    if [ $? = 0 ]; then
+        echo "$srvdir already in ${vicedir}/db/vicetab. Please clean up first."
+        exit 1
+    fi
+    
+    size=""
+    until [ "x$size" != x ]; do
+        echo "Select the maximum number of files for the server."
+        echo "[256K, 1M, 2M, 16M]: "
+        read size
+        case "$size" in
+            256[kK] )
+                echo "$hn   $srvdir   ftree   width=64,depth=3" \
+                     >> ${vicedir}/db/vicetab
+                ;;
+            1[mM] )
+                echo "$hn   $srvdir   ftree   width=32,depth=4" \
+                     >> ${vicedir}/db/vicetab
+                ;;
+            2[mM] )
+                echo "$hn   $srvdir   ftree   width=128,depth=3" \
+                    >> ${vicedir}/db/vicetab
+                ;;
+            16[mM] )
+                echo "$hn   $srvdir   ftree   width=256,depth=3" \
+                    >> ${vicedir}/db/vicetab
+                ;;
+            * )
+                echo "Choose from one of the listed values."
+                size=""
+                ;;
+        esac
+    done
+    echo
+    echo "Server directory $srvdir is set up!"
+else
+    echo
+    echo  "Read vicetab(5) for set up info."
+    echo
+    echo  "Press return to continue"
+    read ok
+fi
+
+echo
diff --git a/coda-src/scripts/vice-setup.in b/coda-src/scripts/vice-setup.in
--- a/coda-src/scripts/vice-setup.in
+++ b/coda-src/scripts/vice-setup.in
@@ -30,19 +30,9 @@ echon() {
 #
 # arguments
 #
-if [ $# = 2 ] ; then
-    if [ x$1 != x-n -o x$2 != x`expr $2 + 0 2>/dev/null` ] ; then
-	echo "Usage: $0 [-n number-of-server-processes]"
-	exit 1
-    fi
-    numservers=$2
-else
-    if [ $# != 0 ] ; then
-	echo "Usage: $0 [-n number-of-server-processes]"
-	exit 1
-    else
-	numservers=1
-    fi
+if [ $# != 0 ] ; then
+    echo "Usage: $0"
+    exit 1
 fi
 
 #
@@ -106,20 +96,6 @@ fi
 conf_directory="`dirname $conf_template`"
 conf="${conf_directory}/`basename $conf_template .ex`"
 
-echon "Do you want the file $conf created? [yes] "
-yesno=""
-read yesno
-if [ x$yesno = x -o x$yesno = xyes -o x$yesno = xy ] ; then
-    mkconf=1
-    mkdir -p "$conf_directory" 2>/dev/null
-else
-    mkconf=0
-    if [ $numservers != 1 ]; then
-	echo "This script can not setup multiple servers without using $conf."
-	exit 1
-    fi
-fi
-
 echon "What is the root directory for your coda server(s)? [/vice] "
 vicedir=""
 read vicedir
@@ -128,50 +104,19 @@ if [ "x$vicedir" = x ] ; then
     vicedir=/vice
 fi
 
-if [ $mkconf = 1 ] ; then
-    @sbindir@/codaconfedit server.conf vicedir $vicedir
-    @sbindir@/codaconfedit server.conf numservers $numservers
-fi
+@sbindir@/codaconfedit server.conf vicedir $vicedir
+#
+# server.conf standard
+#
+@sbindir@/codaconfedit server.conf rvmtruncate 5
+@sbindir@/codaconfedit server.conf trace 100
+
 
 echo "Setting up $vicedir."
 
-for i in auth2 backup db misc vol/remote ; do
+for i in auth2 backup db misc vol/remote srv ; do
     mkdir -p "${vicedir}/$i"
 done
-
-if [ $numservers = 1 ]; then
-    mkdir -p ${vicedir}/srv
-else
-    n=1
-    while [ $n -le $numservers ]; do
-
-	sconf="${conf_directory}/server_$n.conf"
-	dir="${vicedir}/server_$n"
-
-	echo
-	hostname=""
-	while [ x$hostname = x ]; do
-	    echon "Hostname for server $n: "
-	    read hostname
-	done
-
-	cat > $sconf << EOF
-hostname="${hostname}"
-#rvm_log=""
-#rvm_data=""
-#rvm_data_length=""
-#mapprivate=""
-EOF
-
-	echo Creating $dir and subdirectories.
-	mkdir "$dir"
-	for i in backup srv vol ; do
-	    mkdir -p $dir/$i
-	done
-
-	n=`expr $n + 1`
-    done
-fi
 
 echo Directories under $vicedir are set up.
 echo
@@ -318,14 +263,6 @@ esac
 echo $hn > ${vicedir}/hostname
 
 #
-# server.conf standard
-#
-if [ $mkconf = 1 ] ; then
-    @sbindir@/codaconfedit server.conf rvmtruncate 5
-    @sbindir@/codaconfedit server.conf trace 100
-fi
-
-#
 # end of common setup area, now specialize to scm or non scm
 #
 if [ $isscm = Y ]; then
@@ -364,19 +301,8 @@ if [ $isscm = Y ]; then
     [ "$start" ] && @sbindir@/updatesrv
     echo " - Coda update client (updateclnt -h $hn)"
     [ "$start" ] && @sbindir@/updateclnt -h $hn
-
-    if [ $numservers = 1 ]; then
-	echo " - Coda file server (startserver)"
-	[ "$start" ] && @sbindir@/startserver
-    else
-	echo " - Coda file servers:"
-	n=1
-	while [ $n -le $numservers ]; do
-	    echo "   startserver -n $n"
-	    [ "$start" ] && @sbindir@/startserver -n $n
-	    n=`expr $n + 1`
-	done
-    fi
+    echo " - Coda file server (startserver)"
+    [ "$start" ] && ( @sbindir@/startserver || echo "Failed to start the Coda server" )
     echo
 
     if [ "$start" ] ; then
@@ -435,14 +361,5 @@ echo "your first replicated volume."
 #echo
 #echon "Now you can "
 #echo
-#if [ $numservers = 1 ]; then
-#    echo " start the fileserver: startserver &"
-#else
-#    echo " start your fileservers as:
-#    n=1
-#    while [ $n -le $numservers ]; do
-#	echo "    startserver -n $n &"
-#	n=`expr $n + 1`
-#    done
-#fi
+#echo " start the fileserver: startserver &"
 
