Almost complete

diff --git a/configs/Makerules b/configs/Makerules
--- a/configs/Makerules
+++ b/configs/Makerules
@@ -1,28 +1,77 @@
-all: $(SUBDIRS) $(LIBRARIES)  $(HEADERS) $(EXECUTABLES) $(TESTS)
-
-# Catch all, most versions of gnu make use CXXFLAGS for g++, but mach's 
-# version uses C++FLAGS.
-C++FLAGS := $(CXXFLAGS)
+#
+# 	says how to build/install/clean & some specific rules
 
 ###############################################################
-#  jump into subdirs, keep going until failure
+#  recursively descend into subdirs and build targets
 ###############################################################
-subdirinstall: 
+
+all: $(SUBDIRS) $(LIBRARIES) $(HEADERS) $(EXECUTABLES) $(SCRIPTS) $(TESTS)
+
+##################
+# build a single subdirectory
+##################
+ifdef SUBDIRS
+$(SUBDIRS): FORCE
+	${MAKE} -C $@ all; 
+endif
+
+###############################################################
+#  recursively descend into subdirs and install all
+###############################################################
+
+install: $(LIBRARIES) $(HEADERS) $(EXECUTABLES) $(SCRIPTS) $(TESTS)\
+	 hdrinstall bininstall scriptinstall libinstall
 ifdef SUBDIRS
 	@for d in $(SUBDIRS) ; do \
-	    echo "----> entering directory $$d"; \
-	    ${MAKE} -C $$d SUBDIRS= coda; \
-	    if [ $$? != 0 ] ; then echo "----> error in $$d"; exit ; else echo "----> done in $$d"; fi \
+	    ${MAKE} -C $$d install; \
+	    if [ $$? != 0 ] ; then echo "----> error in $$d"; exit 1; \
+	    else true; fi \
 	done
 endif
 
-###################
-# Installation rules
-###################
-ifeq ($(SHOB),)
-coda: subdirinstall $(LIBRARIES) $(EXECUTABLES)  $(TESTS) hdrinstall 
-else
-coda: subdirinstall $(LIBRARIES) $(EXECUTABLES)  $(TESTS) bininstall libinstall hdrinstall 
+###############################################################
+#  recursively descend into subdirs and do hdrinstall and build
+###############################################################
+coda: Coda
+Coda: $(LIBRARIES) $(HEADERS) $(EXECUTABLES) $(SCRIPTS) $(TESTS)\
+	 hdrinstall 
+ifdef SUBDIRS
+	@for d in $(SUBDIRS) ; do \
+	    echo "----> Entering $$d"; \
+	    ${MAKE} -C $$d Coda; \
+	    if [ $$? != 0 ] ; then echo "----> Error in $$d"; exit 1; \
+	    else echo "----> Leaving $$d."; fi \
+	done
+endif
+
+###############################################################
+#  recursively descend into subdirs and build & install client
+###############################################################
+
+client-install: $(LIBRARIES) $(HEADERS) $(EXECUTABLES) $(SCRIPTS) $(TESTS)\
+	 hdrinstall installclient
+ifdef SUBDIRS
+	@for d in $(SUBDIRS) ; do \
+	    echo "----> Entering $$d"; \
+	    ${MAKE} -C $$d client-install; \
+	    if [ $$? != 0 ] ; then echo "----> Error in $$d"; exit 1; \
+	    else echo "----> Leaving $$d."; fi \
+	done
+endif
+
+###############################################################
+#  recursively descend into subdirs and build & install server
+###############################################################
+
+server-install: $(LIBRARIES) $(HEADERS) $(EXECUTABLES) $(SCRIPTS) $(TESTS)\
+	 hdrinstall installserver
+ifdef SUBDIRS
+	@for d in $(SUBDIRS) ; do \
+	    echo "----> Entering $$d"; \
+	    ${MAKE} -C $$d server-install; \
+	    if [ $$? != 0 ] ; then echo "----> Error in $$d"; exit 1; \
+	    else echo "----> Leaving $$d."; fi \
+	done
 endif
 
 #####################
@@ -32,6 +81,45 @@ bininstall: $(EXECUTABLES)
 ifdef EXECUTABLES
 	$(TOPDIR)/tools/our-install 755 $(BINDIR) $?
 	touch bininstall
+endif
+
+#####################
+# install  client or server executables 
+#####################
+
+installclient: cbininstall csbininstall
+
+cbininstall: $(CBINS) 
+ifdef CBINS
+	$(TOPDIR)/tools/our-install 755 $(BINDIR) $?
+endif
+
+csbininstall: $(CSBINS)
+ifdef CSBINS
+	$(TOPDIR)/tools/our-install 755 $(SBINDIR) $?
+endif
+
+installserver: sbininstall ssbininstall
+
+sbininstall: $(SBINS)
+ifdef SBINS
+	$(TOPDIR)/tools/our-install 755 $(BINDIR) $?
+	touch bininstall
+endif
+
+ssbininstall: $(SSBINS)
+ifdef SSBINS
+	$(TOPDIR)/tools/our-install 755 $(SBINDIR) $?
+	touch bininstall
+endif
+
+#####################
+# install scripts
+#####################
+scriptinstall: $(SCRIPTS)
+ifdef SCRIPTS
+	$(TOPDIR)/tools/our-install 755 $(BINDIR) $?
+	touch scriptinstall
 endif
 
 #####################
@@ -48,64 +136,50 @@ endif
 #####################
 hdrinstall: $(HEADERS)
 ifdef HEADERS
+ifdef INCLSUBDIR
+	$(TOPDIR)/tools/our-install 644 $(INCLDIR)/$(INCLSUBDIR) $?
+else
 	$(TOPDIR)/tools/our-install 644 $(INCLDIR) $?
+endif
 	touch hdrinstall
 endif
 
-#####################
-# re-install 
-#####################
-clean-install:
-	$(RM) hdrinstall libinstall
-reinstall: clean-install install
 
-#####################
-# source checkin ... 
-#####################
-srcinstall:
-	SRCDIR=$(srcdir); export SRCDIR; $(ALPHACI)
+###############################################################
+#  local reinstall
+###############################################################
+reinstall: clean-install install
+clean-install:
+	$(RM) bininstall scriptinstall hdrinstall libinstall
 
 ##################
 # cleaning: important too
-# XXX must add rule to remove rp2gen generated .h files
 ##################
 clean: subdirclean realclean
 
 subdirclean:
 ifdef SUBDIRS
 	@for d in $(SUBDIRS) ; do \
-	    echo "----> entering directory $$d"; \
-	    ${MAKE} -C $$d SUBDIRS= realclean; \
-	    echo "----> done in $$d"; \
+	    ${MAKE} -C $$d clean; \
 	done
 endif
 
 realclean:
-	$(RM) *.o *.a *.client.c *.server.c *.multi.c core
-	$(RM) $(EXECUTABLES) $(LIBRARIES) $(TESTS) 
-	$(RM) hdrinstall libinstall bininstall
+	$(RM) *.o *.a 
+	$(RM) *.client.cc *.client.c *.server.cc *.server.c *.multi.cc *.multi.c $(RP2HEADERS)
+	$(RM) $(EXECUTABLES) $(LIBRARIES) $(TESTS) core
+	$(RM) lex.yy.c y.tab.c y.tab.h
+	$(RM) hdrinstall libinstall bininstall scriptinstall
 	$(RM) *.l.c *.pt.c *.l.o *.pt.o
 
-##################
-# build coda from the top
-##################
-topcoda:
-	${MAKE} -C kernel-src/vfs/$(SHORTSYS) hdrinstall 
-ifneq ($(SYS),i386_linux2)
-	${MAKE} -C kernel-src/ifs/$(SHORTSYS) coda; 
-endif
-	${MAKE} -C lib-src coda 
-	${MAKE} -C rvm-src coda 
-	${MAKE} -C coda-src coda
-
-##################
-# build a single subdirectory
-##################
-ifdef SUBDIRS
-$(SUBDIRS): FORCE
-	echo "----> entering $@"; \
-	${MAKE} -C $@ all; 
-endif
+###############################################################
+# 			misc
+###############################################################
+#####################
+# source checkin ... 
+#####################
+srcinstall:
+	SRCDIR=$(srcdir); export SRCDIR; $(ALPHACI)
 
 
 ##################
@@ -116,9 +190,11 @@ showvar:
 	@echo  SHADOWINCLS: $(SHADOWINCLS)
 	@echo  SHADOWRP2: $(SHADOWRP2)
 	@echo  VPATH: $(VPATH)
+	@echo  SHOB: $(SHOB) 
 	@echo  SECSRC: $(SECSRC) 
 	@echo  CFLAGS: $(CFLAGS)
 	@echo  TOPDIR: $(TOPDIR) 
+	@echo  LIBIFS: $(LIBIFS) 
 
 ##################
 # linting
@@ -126,12 +202,12 @@ showvar:
 lint: $(SOURCES)
 	lint $(INCDIRS) $(SOURCES)
 
-##################
-# suffix rules:
-##################
+###############################################################
+# 		build rules
+###############################################################
 
 %.o: %.s
-	$(CPP) -P -D__ASSEMBLY__ $(CFLAGS) $< > $*.ss
+	$(CPP) -P -D__ASSEMBLY__ $(AFLAGS) $< > $*.ss
 	$(AS) -o $@ $*.ss
 	$(RM) $*.ss
 
@@ -142,7 +218,8 @@ lint: $(SOURCES)
 %.doc: %.mss
 	-scribe $?  # Scribe doesn't exist most places.
 
-%.client.cc %.server.cc %.multi.cc %.client.c %.server.c %.multi.c %.h: %.rpc2
+# %.client.cc %.server.cc %.multi.cc %.client.c %.server.c %.multi.c %.h: %.rpc2
+%.client.cc %.server.cc %.multi.cc  %.h: %.rpc2
 	${RP2GEN} ${RP2FLAGS} $<
 
 ifndef NO_LEX
diff --git a/kernel-src/vfs/netbsd.old/Makefile.in b/kernel-src/vfs/netbsd.old/Makefile.in
--- a/kernel-src/vfs/netbsd.old/Makefile.in
+++ b/kernel-src/vfs/netbsd.old/Makefile.in
@@ -1,6 +1,9 @@
-#ifndef _BLURB_
-#define _BLURB_
-#/*
+# TARGETS:
+#	install: put headers in $(INCLDIR)/cfs
+#		THIS IS WRONG!
+#	all: no op
+
+#
 #
 #            Coda: an Experimental Distributed File System
 #                             Release 3.1
@@ -8,63 +11,67 @@
 #          Copyright (c) 1987-1996 Carnegie Mellon University
 #                         All Rights Reserved
 #
-#Permission  to  use, copy, modify and distribute this software and its
-#documentation is hereby granted,  provided  that  both  the  copyright
-#notice  and  this  permission  notice  appear  in  all  copies  of the
-#software, derivative works or  modified  versions,  and  any  portions
-#thereof, and that both notices appear in supporting documentation, and
-#that credit is given to Carnegie Mellon University  in  all  documents
-#and publicity pertaining to direct or indirect use of this code or its
-#derivatives.
-#
-#CODA IS AN EXPERIMENTAL SOFTWARE SYSTEM AND IS  KNOWN  TO  HAVE  BUGS,
-#SOME  OF  WHICH MAY HAVE SERIOUS CONSEQUENCES.  CARNEGIE MELLON ALLOWS
-#FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION.   CARNEGIE  MELLON
-#DISCLAIMS  ANY  LIABILITY  OF  ANY  KIND  FOR  ANY  DAMAGES WHATSOEVER
-#RESULTING DIRECTLY OR INDIRECTLY FROM THE USE OF THIS SOFTWARE  OR  OF
-#ANY DERIVATIVE WORK.
-#
-#Carnegie  Mellon  encourages  users  of  this  software  to return any
-#improvements or extensions that  they  make,  and  to  grant  Carnegie
-#Mellon the rights to redistribute these changes without encumbrance.
-#*/
-#
-#static char *rcsid = "$Header: /afs/cs.cmu.edu/project/coda-braam/src/coda-4.0.1/kernel-src/vfs/mach/RCS/GNUmakefile,v 1.1 1996/11/22 19:15:55 braam Exp braam $";
-#endif /*_BLURB_*/
+# Permission  to  use, copy, modify and distribute this software and its
+# documentation is hereby granted,  provided  that  both  the  copyright
+# notice  and  this  permission  notice  appear  in  all  copies  of the
+# software, derivative works or  modified  versions,  and  any  portions
+# thereof, and that both notices appear in supporting documentation, and
+# that credit is given to Carnegie Mellon University  in  all  documents
+# and publicity pertaining to direct or indirect use of this code or its
+# derivatives.
+# 
+# CODA IS AN EXPERIMENTAL SOFTWARE SYSTEM AND IS  KNOWN  TO  HAVE  BUGS,
+# SOME  OF  WHICH MAY HAVE SERIOUS CONSEQUENCES.  CARNEGIE MELLON ALLOWS
+# FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION.   CARNEGIE  MELLON
+# DISCLAIMS  ANY  LIABILITY  OF  ANY  KIND  FOR  ANY  DAMAGES WHATSOEVER
+# RESULTING DIRECTLY OR INDIRECTLY FROM THE USE OF THIS SOFTWARE  OR  OF
+# ANY DERIVATIVE WORK.
+# 
+# Carnegie  Mellon  encourages  users  of  this  software  to return any
+# improvements or extensions that  they  make,  and  to  grant  Carnegie
+# Mellon the rights to redistribute these changes without encumbrance.
+# 
+# static char *rcsid = "/afs/cs/project/coda-rvb/cvs/src/coda-4.0.1/kernel-src/vfs/netbsd/Makefile.in,v 1.4 1997/01/06 21:28:53 rvb Exp";
 
-
-
-#/* 
-# * Mach Operating System
-# * Copyright (c) 1990 Carnegie-Mellon University
-# * Copyright (c) 1989 Carnegie-Mellon University
-# * All rights reserved.  The CMU software License Agreement specifies
-# * the terms and conditions for use and redistribution.
-# */
-#
-#/*
-# * This code was written for the Coda file system at Carnegie Mellon University.
-# * Contributers include David Steere, James Kistler, and M. Satyanarayanan.
-# */
+#  Mach Operating System
+#  Copyright (c) 1990 Carnegie-Mellon University
+#  Copyright (c) 1989 Carnegie-Mellon University
+#  All rights reserved.  The CMU software License Agreement specifies
+#  the terms and conditions for use and redistribution.
+# 
+#  This code was written for the Coda file system at Carnegie Mellon University.
+#  Contributers include David Steere, James Kistler, and M. Satyanarayanan.
 
 #
 # TODO: Update header dependencies
 #
 
-# Which C compiler to use
-
-
-TOPDIR= @top_srcdir@
+TOPDIR = @top_srcdir@
 srcdir = @srcdir@
 VPATH = @srcdir@
 TOPOBJ= @TOPOBJ@
 
 include $(TOPDIR)/Makeconf
 
+# presto changeo!
+INCLDIR := $(INCLDIR)/cfs
 
-CC = cc
-PLAINC = $(PLAINC?$(PLAINC):cc)
-RP2GEN= ${BINDIR}/rp2gen
+EXECUTABLES = cfsnstat
+LIBRARIES   = pioctl.o
+HEADERS     = cfs.h cfs_LINUX.h cfs_MACH.h cfs_NetBSD.h cfs_opstats.h \
+	      cfs_vnodeops.h cfsio.h cfsnc.h cnode.h mach_vioctl.h
+LIBRARIES   =
+EXECUTABLES =
+
+include $(TOPDIR)/Makerules
+
+##################################################################################
+#		CLEAN UP
+##################################################################################
+
+#CC = cc
+#PLAINC = $(PLAINC?$(PLAINC):cc)
+#RP2GEN= ${BINDIR}/rp2gen
 
 
 # Identify files of interest
@@ -74,13 +81,10 @@ RP2GEN= ${BINDIR}/rp2gen
 #		As an expedient during the port	to NetBSD, I am installing all the .h files
 #		Straighten this out soon....
 
-HFILES = cfs.h cfs_LINUX.h cfs_MACH.h cfs_NetBSD.h cfs_opstats.h cfs_vnodeops.h cfsio.h\
-		cfsnc.h cnode.h mach_vioctl.h
-CFILES = pioctl.c cfsncstat.c
 
 # cfsmount and cfsunmount are obsolete programs and have been 
 # eliminated (Satya, 8/9/96)
-all: pioctl.o cfsncstat
+#all: pioctl.o cfsncstat
 
 pioctl.o: pioctl.c
 	$(CC) $(CFLAGS) -c pioctl.c
@@ -88,27 +92,29 @@ pioctl.o: pioctl.c
 cfsncstat: cfsncstat.c
 	$(PLAINC) $(CFLAGS) -o cfsncstat cfsncstat.c
 
-clean:
-	-rm -rf *.o cfsncstat
+#clean:
+#	-rm -rf *.o cfsncstat
 
 #------------- Installation----------------
-libinstall: all
-	if [ ! -d $(LIBDIR) ]; then mkdir -p $(LIBDIR); fi
-	-cd $(LIBDIR); chmod 0644 pioctl.o 
-	${INSTALL} pioctl.o $(PIOCTL_O)
-	if [ ! -d $(BINDIR) ]; then mkdir -p $(BINDIR); fi
-	-cd $(BINDIR); chmod 0755  cfsncstat
-	${INSTALL} cfsncstat ${BINDIR}
+
+#libinstall: all
+#	if [ ! -d $(LIBDIR) ]; then mkdir -p $(LIBDIR); fi
+#	-cd $(LIBDIR); chmod 0644 pioctl.o 
+#	${INSTALL} pioctl.o $(PIOCTL_O)
+#	if [ ! -d $(BINDIR) ]; then mkdir -p $(BINDIR); fi
+#	-cd $(BINDIR); chmod 0755  cfsncstat
+#	${INSTALL} cfsncstat ${BINDIR}
 
 
-hdrinstall: ${HFILES}
-	-mkdir -p  ${INCLDIR}/cfs
-	-chmod 0644 ${INCLDIR}/cfs/*
-	${INSTALL} $? ${INCLDIR}/cfs
+#hdrinstall: ${HFILES}
+#	-mkdir -p  ${INCLDIR}/cfs
+#	-chmod 0644 ${INCLDIR}/cfs/*
+#	${INSTALL} $? ${INCLDIR}/cfs
 
 
-srcinstall:
+#srcinstall:
 # Manually setenv SUPPRESS_ALPHACI if you want to suppress the RCS checkin by alphaci
-	SRCDIR=$(SRCDIR); export SRCDIR; $(ALPHACI)
+#	SRCDIR=$(SRCDIR); export SRCDIR; $(ALPHACI)
 
-install: libinstall hdrinstall srcinstall 
+#install: libinstall hdrinstall srcinstall 
+
