moved the file

diff --git a/tools/alphaci b/tools/alphaci
--- a/tools/alphaci
+++ b/tools/alphaci
@@ -30,7 +30,7 @@
 #Mellon the rights to redistribute these changes without encumbrance.
 #*/
 #
-#static char *rcsid = "$Header: /afs/cs.cmu.edu/project/coda-braam/src/coda-4.0.1/RCSLINK/./coda-src/scripts/alphaci,v 1.1 1996/11/22 19:06:39 braam Exp $";
+#static char *rcsid = "$Header: /afs/cs.cmu.edu/project/coda-braam/src/coda-4.0.1/tools/RCS/alphaci,v 1.1 1996/11/22 19:48:02 braam Exp braam $";
 #endif /*_BLURB_*/
 
 
@@ -66,7 +66,7 @@
 #Mellon the rights to redistribute these changes without encumbrance.
 #*/
 #
-#static char *rcsid = "$Header: /afs/cs.cmu.edu/project/coda-braam/src/coda-4.0.1/RCSLINK/./coda-src/scripts/alphaci,v 1.1 1996/11/22 19:06:39 braam Exp $";
+#static char *rcsid = "$Header: /afs/cs.cmu.edu/project/coda-braam/src/coda-4.0.1/tools/RCS/alphaci,v 1.1 1996/11/22 19:48:02 braam Exp braam $";
 #endif /*_BLURB_*/
 
 #############################################################################
@@ -121,14 +121,15 @@ if (-e $FREEZE_FILE) then
   exit(1)
 endif
 
-if (!($?MAKEPSD)) then
-  echo "ERROR:  MAKEPSD not set"
-  exit(1)
-endif
+# if (!($?MAKEPSD)) then
+#   echo "ERROR:  MAKEPSD not set"
+#   exit(1)
+# endif
 
 
 # Extract first of possibly many colon-separated pathnames in MAKEPSD
-set CWD = `expr ${MAKEPSD}: : '\([^:]*\):.*'`
+#set CWD = `expr ${MAKEPSD}: : '\([^:]*\):.*'`
+set CWD = $cwd
 
 if (!(-d $CWD)) then
   echo "ERROR:  Can't find directory $CWD"
